name: SKILLS-RELEASE

on:
  workflow_dispatch:

jobs:
  publish-skills:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Extract latest tag from current branch
        id: extract_tag
        shell: bash
        run: |
          LATEST_TAG=$(git tag --merged HEAD --sort=-creatordate | head -n 1)
          if [[ -z "${LATEST_TAG}" ]]; then
            echo "::error::No git tag found for the current branch."
            exit 1
          fi
          echo "latest_tag=${LATEST_TAG}" >> "${GITHUB_OUTPUT}"
          echo "Latest tag: ${LATEST_TAG}"
      - name: Publish Skills
        uses: causalens/skills-upload-action@v0.0.1
        with:
          akeyless-id: ${{ secrets.AKEYLESS_ID }}
          akeyless-key: ${{ secrets.AKEYLESS_KEY }}
          skill-paths: |
            ./skills

